name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      # ソース取得
      - name: Checkout code
        uses: actions/checkout@v4

      # MSBuild セットアップ
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      # vcpkg セットアップ
      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat

      # 依存ライブラリをインストール (manifest モード対応)
      - name: Install dependencies
        run: .\vcpkg\vcpkg.exe install --triplet x64-windows

      # Release ビルド (manifest 有効化 + vcpkg ルート明示)
      - name: Build with MSBuild
        run: msbuild DX12GameEngine.sln `
              /p:Configuration=Release `
              /p:Platform=x64 `
              /p:VcpkgEnableManifest=true `
              /p:VcpkgTriplet=x64-windows `
              /p:VcpkgRoot=${{ github.workspace }}\vcpkg

      # exe + assets パッケージ
      - name: Create package (runtime only)
        run: |
          mkdir package_runtime
          copy x64\Release\DX12GameEngine.exe package_runtime\
          xcopy assets package_runtime\assets /E /I /Y
          powershell Compress-Archive -Path package_runtime\* -DestinationPath DX12GameEngine.zip

      # exe + assets + src パッケージ
      - name: Create package (with source)
        run: |
          mkdir package_src
          copy x64\Release\DX12GameEngine.exe package_src\
          xcopy assets package_src\assets /E /I /Y
          xcopy src package_src\src /E /I /Y
          powershell Compress-Archive -Path package_src\* -DestinationPath DX12GameEngine-with-src.zip

      # GitHub Release にアップロード
      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            DX12GameEngine.zip
            DX12GameEngine-with-src.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
